"""PDF rendering utilities for public learning resources."""

from __future__ import annotations

import re
from io import BytesIO


def _split_markdownish_content(content: str) -> list[tuple[str, str]]:
    """Convert simple markdown-ish resource content into renderable blocks.

    The resource editor intentionally stays lightweight. This parser supports the
    conventions generated by the resource workflow: headings, bullet lists,
    paragraphs, and fenced code blocks.
    """
    blocks: list[tuple[str, str]] = []
    in_code = False
    code_lines: list[str] = []
    paragraph_lines: list[str] = []

    def flush_paragraph() -> None:
        nonlocal paragraph_lines
        if paragraph_lines:
            blocks.append(
                (
                    "paragraph",
                    " ".join(line.strip() for line in paragraph_lines if line.strip()),
                )
            )
            paragraph_lines = []

    for raw_line in (content or "").splitlines():
        line = raw_line.rstrip()
        if line.strip().startswith("```"):
            if in_code:
                blocks.append(("code", "\n".join(code_lines).strip("\n")))
                code_lines = []
                in_code = False
            else:
                flush_paragraph()
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        stripped = line.strip()
        if not stripped:
            flush_paragraph()
            continue
        if stripped.startswith("### "):
            flush_paragraph()
            blocks.append(("heading3", stripped[4:].strip()))
        elif stripped.startswith("## "):
            flush_paragraph()
            blocks.append(("heading2", stripped[3:].strip()))
        elif stripped.startswith("# "):
            flush_paragraph()
            blocks.append(("heading1", stripped[2:].strip()))
        elif stripped.startswith(("- ", "* ")):
            flush_paragraph()
            blocks.append(("bullet", stripped[2:].strip()))
        else:
            paragraph_lines.append(stripped)
    if in_code and code_lines:
        blocks.append(("code", "\n".join(code_lines).strip("\n")))
    flush_paragraph()
    return blocks


def _escape(text: str) -> str:
    return (
        str(text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )


def _filename_slug(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (text or "resource").lower()).strip("-")
    return slug[:80] or "resource"


def resource_pdf_filename(resource) -> str:
    return f"code-with-michael-{_filename_slug(resource.title)}.pdf"


def render_learning_resource_pdf(resource, *, site_url: str = "") -> bytes:
    """Render a branded Code with Michael resource PDF and return bytes."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            ListFlowable,
            ListItem,
            Paragraph,
            Preformatted,
            SimpleDocTemplate,
            Spacer,
        )
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise RuntimeError(
            "ReportLab is required for PDF generation. Install project requirements first."
        ) from exc

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.7 * inch,
        leftMargin=0.7 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.7 * inch,
        title=resource.title,
        author="Code with Michael",
        subject=resource.summary[:180]
        if resource.summary
        else "Beginner Python resource",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CWMTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=29,
        textColor=colors.HexColor("#1E3A8A"),
        spaceAfter=12,
    )
    eyebrow_style = ParagraphStyle(
        "CWMEyebrow",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#2563EB"),
        alignment=TA_CENTER,
        spaceAfter=8,
    )
    summary_style = ParagraphStyle(
        "CWMSummary",
        parent=styles["BodyText"],
        fontSize=12,
        leading=17,
        textColor=colors.HexColor("#334155"),
        spaceAfter=14,
    )
    h2_style = ParagraphStyle(
        "CWMHeading2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=12,
        spaceAfter=6,
    )
    h3_style = ParagraphStyle(
        "CWMHeading3",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#1E293B"),
        spaceBefore=8,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "CWMBody",
        parent=styles["BodyText"],
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#111827"),
        spaceAfter=7,
    )
    tip_style = ParagraphStyle(
        "CWMTip",
        parent=styles["BodyText"],
        fontSize=10.5,
        leading=15,
        backColor=colors.HexColor("#EFF6FF"),
        borderColor=colors.HexColor("#93C5FD"),
        borderWidth=0.8,
        borderPadding=8,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=6,
        spaceAfter=12,
    )
    code_style = ParagraphStyle(
        "CWMCode",
        parent=styles["Code"],
        fontName="Courier",
        fontSize=8.8,
        leading=11.5,
        leftIndent=8,
        rightIndent=8,
        backColor=colors.HexColor("#F8FAFC"),
        borderColor=colors.HexColor("#CBD5E1"),
        borderWidth=0.5,
        borderPadding=7,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=4,
        spaceAfter=9,
    )
    bullet_style = ParagraphStyle(
        "CWMBullet",
        parent=body_style,
        leftIndent=12,
        firstLineIndent=0,
    )
    footer_note = (
        resource.pdf_footer_note
        or "Practice the example, change one thing, and run it again."
    )

    story = [
        Paragraph("CODE WITH MICHAEL - BEGINNER PYTHON RESOURCE", eyebrow_style),
        Paragraph(_escape(resource.title), title_style),
    ]
    if resource.summary:
        story.append(Paragraph(_escape(resource.summary), summary_style))
    meta = " | ".join(
        part
        for part in [
            resource.get_resource_type_display(),
            resource.get_difficulty_display(),
            f"{resource.estimated_read_minutes} min read",
            resource.category.name if resource.category else "",
        ]
        if part
    )
    if meta:
        story.append(Paragraph(_escape(meta), body_style))
    if resource.beginner_tip:
        story.append(
            Paragraph(
                f"<b>Beginner tip:</b> {_escape(resource.beginner_tip)}", tip_style
            )
        )

    pending_bullets: list[str] = []

    def flush_bullets() -> None:
        nonlocal pending_bullets
        if pending_bullets:
            story.append(
                ListFlowable(
                    [
                        ListItem(Paragraph(_escape(item), bullet_style), leftIndent=8)
                        for item in pending_bullets
                    ],
                    bulletType="bullet",
                    start="circle",
                    leftIndent=16,
                )
            )
            story.append(Spacer(1, 4))
            pending_bullets = []

    for block_type, text in _split_markdownish_content(resource.content):
        if block_type != "bullet":
            flush_bullets()
        if block_type == "heading1":
            story.append(Paragraph(_escape(text), h2_style))
        elif block_type == "heading2":
            story.append(Paragraph(_escape(text), h2_style))
        elif block_type == "heading3":
            story.append(Paragraph(_escape(text), h3_style))
        elif block_type == "paragraph":
            story.append(Paragraph(_escape(text), body_style))
        elif block_type == "code":
            story.append(Preformatted(text or " ", code_style, maxLineLength=86))
        elif block_type == "bullet":
            pending_bullets.append(text)
    flush_bullets()

    related = list(
        resource.related_lessons.filter(website_status__in=["ready", "published"])[:6]
    )
    if related:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Related lessons", h2_style))
        for lesson in related:
            story.append(Paragraph(_escape(f"- {lesson.title}"), body_style))

    story.append(Spacer(1, 14))
    story.append(Paragraph(_escape(footer_note), tip_style))
    if site_url:
        story.append(
            Paragraph(_escape(f"More beginner Python lessons: {site_url}"), body_style)
        )

    def draw_footer(canvas, document):
        canvas.saveState()
        width, _height = letter
        canvas.setStrokeColor(colors.HexColor("#E2E8F0"))
        canvas.line(
            document.leftMargin, 0.52 * inch, width - document.rightMargin, 0.52 * inch
        )
        canvas.setFillColor(colors.HexColor("#64748B"))
        canvas.setFont("Helvetica", 8)
        canvas.drawString(document.leftMargin, 0.35 * inch, "Code with Michael")
        canvas.drawRightString(
            width - document.rightMargin, 0.35 * inch, f"Page {document.page}"
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=draw_footer, onLaterPages=draw_footer)
    return buffer.getvalue()
