# Generated by Django 6.0.3 on 2026-07-26 16:22

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('caption', 'Caption'), ('lesson_draft', 'Lesson draft'), ('improvement', 'Lesson improvement'), ('quiz', 'Quiz'), ('challenge', 'Challenge')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('reasoning_effort', models.CharField(blank=True, max_length=20)),
                ('response_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('instructions', models.TextField(blank=True)),
                ('prompt', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('input_price_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cached_input_price_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('output_price_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cache_write_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.250'), max_digits=5)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Code with Michael', max_length=120)),
                ('social_handle', models.CharField(default='@code_with_michael', max_length=80)),
                ('default_accent', models.CharField(default='#3776AB', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a six-digit hex color such as #3776AB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('background_color', models.CharField(default='#0A0C16', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a six-digit hex color such as #3776AB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('default_call_to_action', models.CharField(default='Save this post and follow for more Python lessons.', max_length=180)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'brand profile',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('accent_color', models.CharField(default='#3776AB', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a six-digit hex color such as #3776AB.', regex='^#[0-9A-Fa-f]{6}$')])),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GraphicTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('template_type', models.CharField(choices=[('lesson', 'Lesson explainer'), ('project', 'Project series'), ('challenge', 'Challenge / quiz'), ('answer', 'Answer'), ('spot_bug', 'Spot the bug'), ('mini_program', 'Mini program'), ('comparison', 'Comparison / cheat sheet'), ('error', 'Errors / common mistakes'), ('community', 'Community / celebration')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('text', 'Explanation'), ('code', 'Code'), ('output', 'Output'), ('callout', 'Callout / tip'), ('list', 'List'), ('image', 'Image'), ('quiz', 'Quiz'), ('challenge', 'Challenge'), ('comparison', 'Comparison')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('content', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_lessons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AIModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=80)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('input_per_million', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cached_input_per_million', models.DecimalField(decimal_places=4, max_digits=10)),
                ('output_per_million', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cache_write_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.250'), max_digits=5)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-effective_from', 'model'),
                'constraints': [models.UniqueConstraint(fields=('model', 'effective_from'), name='unique_model_price_date')],
            },
        ),
        migrations.CreateModel(
            name='CaptionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('threads', 'Threads')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caption_drafts', to='studio.aigeneration')),
            ],
            options={
                'ordering': ('platform', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GraphicAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_format', models.CharField(choices=[('instagram_square', 'Instagram / Facebook square'), ('instagram_portrait', 'Instagram / Threads portrait'), ('story', 'Instagram / Facebook story'), ('facebook_landscape', 'Facebook landscape')], max_length=30)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('slide_number', models.PositiveSmallIntegerField(default=1)),
                ('file', models.ImageField(blank=True, upload_to='generated/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='studio.graphictemplate')),
            ],
            options={
                'ordering': ('output_format', 'slide_number', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=230, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('draft', 'Draft'), ('review', 'In review'), ('ready', 'Ready'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='idea', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], default='beginner', max_length=20)),
                ('series_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a six-digit hex color such as #3776AB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('call_to_action', models.CharField(blank=True, max_length=220)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('internal_notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='studio.category')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
