# Generated by Django 6.0.3 on 2026-07-26 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graphicasset',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.lesson'),
        ),
        migrations.AddField(
            model_name='captiondraft',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='studio.lesson'),
        ),
        migrations.AddField(
            model_name='aigeneration',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to='studio.lesson'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='studio.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='studio.series'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='studio.tag'),
        ),
        migrations.AddConstraint(
            model_name='lessonblock',
            constraint=models.UniqueConstraint(fields=('lesson', 'position'), name='unique_lesson_block_position'),
        ),
    ]
