# Generated by ChatGPT for Code with Michael Content Studio phase 3.

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0006_lesson_learning_fields_platform_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ("title", models.CharField(max_length=180)),
                ("prompt", models.TextField(help_text="Describe the task the beginner should complete.")),
                ("starter_code", models.TextField(blank=True)),
                ("solution_code", models.TextField(blank=True)),
                ("expected_output", models.TextField(blank=True)),
                ("hint_1", models.CharField(blank=True, max_length=240)),
                ("hint_2", models.CharField(blank=True, max_length=240)),
                ("validation_mode", models.CharField(choices=[("exact_output", "Exact output match"), ("contains_output", "Output contains text"), ("manual", "Manual review")], default="exact_output", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="code_challenges", to="studio.lesson")),
            ],
            options={"ordering": ("position", "pk")},
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ("question_type", models.CharField(choices=[("multiple_choice", "Multiple choice"), ("true_false", "True / false"), ("short_answer", "Short answer")], default="multiple_choice", max_length=30)),
                ("prompt", models.TextField(help_text="Ask one clear beginner-friendly question.")),
                ("explanation", models.TextField(blank=True, help_text="Explain why the correct answer is correct in plain English.")),
                ("is_active", models.BooleanField(default=True)),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_questions", to="studio.lesson")),
            ],
            options={"ordering": ("position", "pk")},
        ),
        migrations.CreateModel(
            name="ChallengeAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=80)),
                ("submitted_code", models.TextField()),
                ("observed_output", models.TextField(blank=True)),
                ("passed", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True)),
                ("challenge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="studio.codechallenge")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="challenge_attempts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="QuizChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ("text", models.CharField(max_length=400)),
                ("is_correct", models.BooleanField(default=False)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="choices", to="studio.quizquestion")),
            ],
            options={"ordering": ("position", "pk")},
        ),
        migrations.AddConstraint(model_name="codechallenge", constraint=models.UniqueConstraint(fields=("lesson", "position"), name="unique_lesson_challenge_position")),
        migrations.AddConstraint(model_name="quizquestion", constraint=models.UniqueConstraint(fields=("lesson", "position"), name="unique_lesson_quiz_position")),
        migrations.AddConstraint(model_name="quizchoice", constraint=models.UniqueConstraint(fields=("question", "position"), name="unique_quiz_choice_position")),
    ]
