# Generated by ChatGPT for Code with Michael Content Studio phase 11.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0009_challenge_test_cases"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(choices=[("facebook", "Facebook"), ("instagram", "Instagram"), ("threads", "Threads"), ("website", "Website"), ("email", "Email list"), ("other", "Other")], db_index=True, max_length=20)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now, help_text="When this content was posted or published.")),
                ("post_url", models.URLField(blank=True, help_text="Direct URL to the published post, page, or email archive.")),
                ("caption_text", models.TextField(blank=True, help_text="Snapshot of the final caption used. This stays intact even if the caption draft changes later.")),
                ("notes", models.TextField(blank=True)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("saves", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("new_followers", models.IntegerField(default=0)),
                ("follower_count_after", models.PositiveIntegerField(default=0)),
                ("caption", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="publishing_records", to="studio.captiondraft")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="publishing_records_created", to=settings.AUTH_USER_MODEL)),
                ("graphic", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="publishing_records", to="studio.graphicasset")),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publishing_records", to="studio.lesson")),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
                "indexes": [models.Index(fields=["platform", "published_at"], name="studio_publ_platfor_75f9e2_idx"), models.Index(fields=["lesson", "platform"], name="studio_publ_lesson__52af79_idx")],
            },
        ),
    ]
