# Generated by ChatGPT for Code with Michael Content Studio phase 12.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0010_publishing_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(choices=[("facebook", "Facebook"), ("instagram", "Instagram"), ("threads", "Threads"), ("website", "Website"), ("email", "Email list"), ("other", "Other")], db_index=True, max_length=20)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("idea", "Idea"), ("planned", "Planned"), ("drafted", "Drafted"), ("ready", "Ready"), ("scheduled", "Scheduled"), ("posted", "Posted"), ("skipped", "Skipped")], db_index=True, default="planned", max_length=20)),
                ("carousel_template", models.CharField(blank=True, help_text="Optional social carousel format, such as beginner_mistake or spot_the_bug.", max_length=80)),
                ("post_goal", models.CharField(blank=True, help_text="What this post should accomplish, such as reach beginners, drive website clicks, or promote a challenge.", max_length=180)),
                ("notes", models.TextField(blank=True)),
                ("caption", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_plans", to="studio.captiondraft")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_plans_created", to=settings.AUTH_USER_MODEL)),
                ("graphic", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_plans", to="studio.graphicasset")),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="content_plans", to="studio.lesson")),
                ("publishing_record", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="content_plan", to="studio.publishingrecord")),
            ],
            options={
                "ordering": ("scheduled_at", "platform", "lesson__title"),
                "indexes": [models.Index(fields=["scheduled_at", "platform"], name="studio_cont_sched__26d7b1_idx"), models.Index(fields=["status", "scheduled_at"], name="studio_cont_status_2f530c_idx"), models.Index(fields=["lesson", "platform"], name="studio_cont_lesson__65ef04_idx")],
            },
        ),
    ]
