# Generated by ChatGPT for Code with Michael Content Studio phase 17.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0012_newsletter_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("subject", models.CharField(max_length=180)),
                ("preview_text", models.CharField(blank=True, max_length=220)),
                ("body", models.TextField(help_text="Draft email body. Review before sending in your email platform.")),
                ("call_to_action", models.CharField(blank=True, max_length=180)),
                ("cta_url", models.URLField(blank=True)),
                ("status", models.CharField(choices=[("idea", "Idea"), ("draft", "Draft"), ("ready", "Ready"), ("scheduled", "Scheduled"), ("sent", "Sent"), ("archived", "Archived")], db_index=True, default="draft", max_length=20)),
                ("target_segment", models.CharField(choices=[("all_active", "All active subscribers"), ("beginner", "Beginner learners"), ("intermediate", "Intermediate learners"), ("advanced", "Advanced learners"), ("manual", "Manual segment")], db_index=True, default="all_active", max_length=30)),
                ("scheduled_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("estimated_recipients", models.PositiveIntegerField(default=0)),
                ("actual_recipients", models.PositiveIntegerField(default=0)),
                ("opens", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("unsubscribes", models.PositiveIntegerField(default=0)),
                ("bounces", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("content_plan", models.OneToOneField(blank=True, help_text="Optional planned email slot connected to this campaign.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="newsletter_campaign", to="studio.contentplan")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="newsletter_campaigns_created", to=settings.AUTH_USER_MODEL)),
                ("lesson", models.ForeignKey(blank=True, help_text="Optional lesson this email promotes or teaches from.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="newsletter_campaigns", to="studio.lesson")),
                ("publishing_record", models.OneToOneField(blank=True, help_text="Optional sent email performance record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="newsletter_campaign", to="studio.publishingrecord")),
            ],
            options={
                "ordering": ("-scheduled_at", "-created_at"),
                "indexes": [models.Index(fields=["status", "scheduled_at"], name="studio_news_status_0f2637_idx"), models.Index(fields=["target_segment", "scheduled_at"], name="studio_news_target_1ee4f5_idx")],
            },
        ),
    ]
