# Generated by Code with Michael content studio phase 18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0013_newsletter_campaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterMetricImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("mailchimp", "Mailchimp"), ("beehiiv", "Beehiiv"), ("convertkit", "ConvertKit"), ("manual", "Manual / pasted"), ("other", "Other")], default="manual", max_length=30)),
                ("source_filename", models.CharField(blank=True, max_length=220)),
                ("raw_payload", models.TextField(blank=True)),
                ("normalized_data", models.JSONField(blank=True, default=dict)),
                ("actual_recipients", models.PositiveIntegerField(default=0)),
                ("opens", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("unsubscribes", models.PositiveIntegerField(default=0)),
                ("bounces", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metric_imports", to="studio.newslettercampaign")),
                ("imported_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="newsletter_metric_imports", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-applied_at", "-created_at"),
                "indexes": [
                    models.Index(fields=["campaign", "applied_at"], name="studio_news_campaign_410017_idx"),
                    models.Index(fields=["provider", "applied_at"], name="studio_news_provider_4f391c_idx"),
                ],
            },
        ),
    ]
