# Generated by Code with Michael content studio phase 20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0015_subscriber_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettercampaign",
            name="external_provider",
            field=models.CharField(choices=[("none", "Not connected"), ("mailchimp", "Mailchimp"), ("beehiiv", "Beehiiv"), ("convertkit", "ConvertKit"), ("other", "Other")], db_index=True, default="none", help_text="Email service provider this campaign is prepared to sync with.", max_length=30),
        ),
        migrations.AddField(
            model_name="newslettercampaign",
            name="external_campaign_id",
            field=models.CharField(blank=True, help_text="Campaign ID from Mailchimp, Beehiiv, ConvertKit, or another provider.", max_length=160),
        ),
        migrations.AddField(
            model_name="newslettercampaign",
            name="external_audience_id",
            field=models.CharField(blank=True, help_text="Audience, list, publication, or form ID used by the email provider.", max_length=160),
        ),
        migrations.AddField(
            model_name="newslettercampaign",
            name="provider_url",
            field=models.URLField(blank=True, help_text="Optional provider dashboard URL for this campaign."),
        ),
        migrations.AddField(
            model_name="newslettercampaign",
            name="provider_sync_status",
            field=models.CharField(choices=[("not_connected", "Not connected"), ("ready", "Ready to sync"), ("synced", "Synced"), ("needs_review", "Needs review"), ("error", "Error")], db_index=True, default="not_connected", max_length=30),
        ),
        migrations.AddField(
            model_name="newslettercampaign",
            name="provider_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettercampaign",
            name="provider_notes",
            field=models.TextField(blank=True, help_text="Private notes about provider setup, sync issues, field mapping, or manual actions."),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="external_provider",
            field=models.CharField(choices=[("none", "Not connected"), ("mailchimp", "Mailchimp"), ("beehiiv", "Beehiiv"), ("convertkit", "ConvertKit"), ("other", "Other")], db_index=True, default="none", help_text="Email service provider where this contact lives.", max_length=30),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="external_contact_id",
            field=models.CharField(blank=True, help_text="Contact/subscriber ID from the email provider.", max_length=160),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="external_list_id",
            field=models.CharField(blank=True, help_text="Provider list, audience, publication, or form ID for this subscriber.", max_length=160),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="provider_sync_status",
            field=models.CharField(choices=[("not_connected", "Not connected"), ("ready", "Ready to sync"), ("synced", "Synced"), ("needs_review", "Needs review"), ("error", "Error")], db_index=True, default="not_connected", max_length=30),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="provider_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="provider_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subscribersegment",
            name="external_provider",
            field=models.CharField(choices=[("none", "Not connected"), ("mailchimp", "Mailchimp"), ("beehiiv", "Beehiiv"), ("convertkit", "ConvertKit"), ("other", "Other")], db_index=True, default="none", help_text="Email provider this saved segment is intended to map to.", max_length=30),
        ),
        migrations.AddField(
            model_name="subscribersegment",
            name="external_segment_id",
            field=models.CharField(blank=True, help_text="Segment, tag, audience, or saved filter ID from the provider.", max_length=160),
        ),
        migrations.AddField(
            model_name="subscribersegment",
            name="external_audience_id",
            field=models.CharField(blank=True, help_text="Provider audience/list/publication ID that contains this segment.", max_length=160),
        ),
        migrations.AddField(
            model_name="subscribersegment",
            name="provider_sync_status",
            field=models.CharField(choices=[("not_connected", "Not connected"), ("ready", "Ready to sync"), ("synced", "Synced"), ("needs_review", "Needs review"), ("error", "Error")], db_index=True, default="not_connected", max_length=30),
        ),
        migrations.AddField(
            model_name="subscribersegment",
            name="provider_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscribersegment",
            name="provider_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="newslettercampaign",
            index=models.Index(fields=["external_provider", "provider_sync_status"], name="studio_news_external_3d89f0_idx"),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(fields=["external_provider", "provider_sync_status"], name="studio_news_external_6b2a71_idx"),
        ),
        migrations.AddIndex(
            model_name="subscribersegment",
            index=models.Index(fields=["external_provider", "provider_sync_status"], name="studio_subs_external_d843a6_idx"),
        ),
    ]
