# Generated by Code with Michael content studio phase 22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0016_email_provider_sync_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(blank=True, max_length=230, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("resource_type", models.CharField(choices=[("cheat_sheet", "Cheat sheet"), ("common_error", "Common Python error"), ("setup_guide", "Setup guide"), ("practice_reference", "Practice reference"), ("glossary", "Python vocabulary"), ("download", "Downloadable reference")], db_index=True, default="cheat_sheet", max_length=30)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ready", "Ready"), ("published", "Published"), ("archived", "Archived")], db_index=True, default="draft", max_length=20)),
                ("difficulty", models.CharField(choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced"), ("mixed", "Mixed")], default="beginner", max_length=20)),
                ("featured", models.BooleanField(db_index=True, default=False)),
                ("content", models.TextField(blank=True, help_text="Main public resource content. Markdown-style headings and code fences are okay.")),
                ("beginner_tip", models.CharField(blank=True, max_length=240)),
                ("downloadable_file", models.FileField(blank=True, upload_to="resources/")),
                ("external_url", models.URLField(blank=True)),
                ("estimated_read_minutes", models.PositiveSmallIntegerField(default=5)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
                ("internal_notes", models.TextField(blank=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="learning_resources", to="studio.category")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="learning_resources_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="learning_resources_updated", to=settings.AUTH_USER_MODEL)),
                ("related_lessons", models.ManyToManyField(blank=True, related_name="learning_resources", to="studio.lesson")),
                ("tags", models.ManyToManyField(blank=True, related_name="learning_resources", to="studio.tag")),
            ],
            options={
                "ordering": ("resource_type", "title"),
            },
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["status", "resource_type"], name="studio_lear_status_39960c_idx"),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(fields=["featured", "status"], name="studio_lear_feature_23f4c6_idx"),
        ),
    ]
