# Generated by Code with Michael Content Studio phase 24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0017_learning_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="pdf_download_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show a generated branded PDF download on the public resource page.",
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="pdf_footer_note",
            field=models.CharField(
                blank=True,
                help_text="Optional short note printed in the footer of generated PDFs.",
                max_length=180,
            ),
        ),
    ]
