# Generated by ChatGPT phase 27.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0020_resource_performance_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceLessonConversionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(choices=[("lesson_view", "Lesson view"), ("account_signup", "Account signup"), ("quiz_attempt", "Quiz attempt"), ("challenge_attempt", "Challenge attempt"), ("lesson_complete", "Lesson complete")], db_index=True, max_length=30)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("attribution_event_type", models.CharField(blank=True, choices=[("view", "Resource view"), ("pdf_unlock", "PDF unlock"), ("pdf_download", "PDF download")], max_length=20)),
                ("attribution_source_url", models.CharField(blank=True, max_length=300)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("lesson", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_conversion_events", to="studio.lesson")),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lesson_conversion_events", to="studio.learningresource")),
                ("source_event", models.ForeignKey(blank=True, help_text="The resource view/unlock/download event that received attribution when available.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lesson_conversion_events", to="studio.resourceperformanceevent")),
                ("subscriber", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_lesson_conversion_events", to="studio.newslettersubscriber")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_lesson_conversion_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(fields=["resource", "event_type", "occurred_at"], name="studio_reso_resourc_8b9751_idx"),
                    models.Index(fields=["lesson", "event_type", "occurred_at"], name="studio_reso_lesson__e3e47d_idx"),
                    models.Index(fields=["event_type", "occurred_at"], name="studio_reso_event_t_9f8277_idx"),
                    models.Index(fields=["email", "occurred_at"], name="studio_reso_email_9f9c15_idx"),
                ],
            },
        ),
    ]
