# Generated by Django 6.0.3 on 2026-07-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_websiteexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='enable_playground',
            field=models.BooleanField(default=False, help_text='Allow code blocks to run in the browser-based Python playground.'),
        ),
    ]
