# Generated by ChatGPT for Code with Michael Content Studio phase 16.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0011_content_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(choices=[("active", "Active"), ("unsubscribed", "Unsubscribed"), ("bounced", "Bounced")], db_index=True, default="active", max_length=20)),
                ("source", models.CharField(choices=[("learn_home", "Learn homepage"), ("lesson", "Lesson page"), ("playground", "Playground"), ("import", "Imported"), ("studio", "Studio"), ("other", "Other")], db_index=True, default="learn_home", max_length=30)),
                ("source_url", models.CharField(blank=True, max_length=300)),
                ("consent_text", models.CharField(default="Send me beginner Python lessons, practice prompts, and Code with Michael updates.", max_length=240)),
                ("subscribed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("source_lesson", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="newsletter_subscribers", to="studio.lesson")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="newsletter_subscriptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-subscribed_at", "email"),
                "indexes": [models.Index(fields=["status", "subscribed_at"], name="studio_news_status_018afa_idx"), models.Index(fields=["source", "subscribed_at"], name="studio_news_source_9a8b8b_idx")],
            },
        ),
    ]
