# Generated by Code with Michael content studio phase 19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0014_newsletter_metric_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriberSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("status_filter", models.CharField(blank=True, choices=[("any", "Any status"), ("active", "Active"), ("unsubscribed", "Unsubscribed"), ("bounced", "Bounced")], default="active", help_text="Subscriber status to include. Active is safest for campaigns.", max_length=20)),
                ("source_filter", models.CharField(blank=True, choices=[("any", "Any source"), ("learn_home", "Learn homepage"), ("lesson", "Lesson page"), ("playground", "Playground"), ("import", "Imported"), ("studio", "Studio"), ("other", "Other")], default="any", help_text="Limit the segment to subscribers from a specific signup source.", max_length=30)),
                ("skill_level_filter", models.CharField(blank=True, choices=[("any", "Any skill level"), ("new", "Brand new"), ("beginner", "Beginner"), ("returning", "Returning learner"), ("intermediate", "Intermediate")], default="any", help_text="Limit the segment to learners with this profile skill level.", max_length=20)),
                ("subscribed_after", models.DateField(blank=True, null=True)),
                ("subscribed_before", models.DateField(blank=True, null=True)),
                ("subscribed_within_days", models.PositiveSmallIntegerField(blank=True, help_text="Optional rolling recency window, such as 30 for subscribers from the last month.", null=True)),
                ("search_text", models.CharField(blank=True, help_text="Optional keyword match across email, first name, notes, and source lesson title.", max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscriber_segments_created", to=settings.AUTH_USER_MODEL)),
                ("source_lesson", models.ForeignKey(blank=True, help_text="Optional lesson that captured the subscriber.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscriber_segments", to="studio.lesson")),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["is_active", "status_filter"], name="studio_subs_is_acti_8d0b3b_idx"),
                    models.Index(fields=["source_filter", "skill_level_filter"], name="studio_subs_source__43f8d2_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="newslettercampaign",
            name="saved_segment",
            field=models.ForeignKey(blank=True, help_text="Optional saved subscriber segment. Use this for repeatable campaign targeting rules.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaigns", to="studio.subscribersegment"),
        ),
    ]
