# Generated by Django 6.0.3 on 2026-07-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_email_provider_sync_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentplan',
            new_name='studio_cont_schedul_9e6c57_idx',
            old_name='studio_cont_sched__26d7b1_idx',
        ),
        migrations.RenameIndex(
            model_name='contentplan',
            new_name='studio_cont_status_dabb9a_idx',
            old_name='studio_cont_status_2f530c_idx',
        ),
        migrations.RenameIndex(
            model_name='contentplan',
            new_name='studio_cont_lesson__06c40c_idx',
            old_name='studio_cont_lesson__65ef04_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettercampaign',
            new_name='studio_news_status_a1d960_idx',
            old_name='studio_news_status_0f2637_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettercampaign',
            new_name='studio_news_target__d24364_idx',
            old_name='studio_news_target_1ee4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettercampaign',
            new_name='studio_news_externa_cad5b3_idx',
            old_name='studio_news_external_3d89f0_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettermetricimport',
            new_name='studio_news_campaig_807a8b_idx',
            old_name='studio_news_campaign_410017_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettermetricimport',
            new_name='studio_news_provide_849ba9_idx',
            old_name='studio_news_provider_4f391c_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='studio_news_status_b90998_idx',
            old_name='studio_news_status_018afa_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='studio_news_source_e45842_idx',
            old_name='studio_news_source_9a8b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='studio_news_externa_a5a400_idx',
            old_name='studio_news_external_6b2a71_idx',
        ),
        migrations.RenameIndex(
            model_name='publishingrecord',
            new_name='studio_publ_platfor_aaecf5_idx',
            old_name='studio_publ_platfor_75f9e2_idx',
        ),
        migrations.RenameIndex(
            model_name='publishingrecord',
            new_name='studio_publ_lesson__df4b87_idx',
            old_name='studio_publ_lesson__52af79_idx',
        ),
        migrations.RenameIndex(
            model_name='subscribersegment',
            new_name='studio_subs_is_acti_0b3e2e_idx',
            old_name='studio_subs_is_acti_8d0b3b_idx',
        ),
        migrations.RenameIndex(
            model_name='subscribersegment',
            new_name='studio_subs_source__dc3eef_idx',
            old_name='studio_subs_source__43f8d2_idx',
        ),
        migrations.RenameIndex(
            model_name='subscribersegment',
            new_name='studio_subs_externa_b96f43_idx',
            old_name='studio_subs_external_d843a6_idx',
        ),
    ]
