# Generated by ChatGPT for Code with Michael Content Studio phase 25
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0018_learning_resource_pdf_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="source",
            field=models.CharField(
                choices=[
                    ("learn_home", "Learn homepage"),
                    ("lesson", "Lesson page"),
                    ("resource", "Resource download"),
                    ("playground", "Playground"),
                    ("import", "Imported"),
                    ("studio", "Studio"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="learn_home",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="source_resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Resource that captured this subscriber, especially PDF lead magnets.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newsletter_subscribers",
                to="studio.learningresource",
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="pdf_requires_email",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Require newsletter signup before the generated PDF can be downloaded.",
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="pdf_lead_magnet_headline",
            field=models.CharField(
                blank=True,
                help_text="Optional headline for the email-gated PDF download page.",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="pdf_lead_magnet_description",
            field=models.TextField(
                blank=True,
                help_text="Optional short description shown before the email signup form.",
            ),
        ),
        migrations.CreateModel(
            name="ResourceLeadMagnetAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("source_url", models.CharField(blank=True, max_length=300)),
                ("access_granted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lead_magnet_accesses", to="studio.learningresource")),
                ("subscriber", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_lead_magnet_accesses", to="studio.newslettersubscriber")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_lead_magnet_accesses", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-access_granted_at", "email"),
                "unique_together": {("resource", "email")},
            },
        ),
        migrations.AddIndex(
            model_name="resourceleadmagnetaccess",
            index=models.Index(fields=["resource", "access_granted_at"], name="studio_reso_resourc_b88487_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceleadmagnetaccess",
            index=models.Index(fields=["email", "access_granted_at"], name="studio_reso_email_8c3345_idx"),
        ),
    ]
