# Generated by ChatGPT phase 28.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0021_resource_lesson_conversion_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCTA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(999)])),
                ("target_type", models.CharField(choices=[("lesson", "Start matching lesson"), ("quiz", "Try quiz next"), ("challenge", "Practice with a challenge"), ("pdf", "Download resource PDF"), ("newsletter", "Join the newsletter"), ("external", "External link")], db_index=True, default="lesson", max_length=30)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("button_label", models.CharField(default="Start now", max_length=80)),
                ("target_url", models.CharField(blank=True, help_text="External URL or custom path. Leave blank for lesson, PDF, and newsletter CTA types.", max_length=300)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cta_blocks", to="studio.learningresource")),
                ("target_lesson", models.ForeignKey(blank=True, help_text="Lesson to send learners to for lesson, quiz, and challenge CTA blocks.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_ctas", to="studio.lesson")),
            ],
            options={
                "ordering": ("position", "pk"),
                "indexes": [
                    models.Index(fields=["resource", "is_active", "position"], name="studio_reso_res_is_a_4d6f2d_idx"),
                    models.Index(fields=["target_type", "is_active"], name="studio_reso_targ_is_3f85cc_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("resource", "position"), name="unique_resource_cta_position")],
            },
        ),
        migrations.CreateModel(
            name="ResourceCTAClickEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("source_url", models.CharField(blank=True, max_length=300)),
                ("target_url", models.CharField(blank=True, max_length=300)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("cta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="click_events", to="studio.resourcecta")),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cta_click_events", to="studio.learningresource")),
                ("subscriber", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_cta_click_events", to="studio.newslettersubscriber")),
                ("target_lesson", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_cta_click_events", to="studio.lesson")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_cta_click_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(fields=["resource", "occurred_at"], name="studio_reso_res_occ_b39034_idx"),
                    models.Index(fields=["cta", "occurred_at"], name="studio_reso_cta_occ_4e1ed2_idx"),
                    models.Index(fields=["target_lesson", "occurred_at"], name="studio_reso_targ_oc_52dafc_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="resourcelessonconversionevent",
            name="cta",
            field=models.ForeignKey(blank=True, help_text="Resource CTA block that received click attribution when available.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversion_events", to="studio.resourcecta"),
        ),
        migrations.AddField(
            model_name="resourcelessonconversionevent",
            name="cta_click",
            field=models.ForeignKey(blank=True, help_text="Specific CTA click that received attribution when available.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversion_events", to="studio.resourcectaclickevent"),
        ),
    ]
