# Generated by Code with Michael Studio phase 30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0022_resource_cta_blocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCTARecommendationFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recommendation_key", models.CharField(db_index=True, max_length=120)),
                ("target_type", models.CharField(choices=[("lesson", "Start matching lesson"), ("quiz", "Try quiz next"), ("challenge", "Practice with a challenge"), ("pdf", "Download resource PDF"), ("newsletter", "Join the newsletter"), ("external", "External link")], max_length=30)),
                ("title", models.CharField(max_length=180)),
                ("score", models.IntegerField(default=0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("shown", "Shown / ignored"), ("accepted", "Accepted"), ("dismissed", "Dismissed")], db_index=True, default="shown", max_length=20)),
                ("times_shown", models.PositiveIntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("applied_cta", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recommendation_feedback", to="studio.resourcecta")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_cta_recommendations_created", to=settings.AUTH_USER_MODEL)),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cta_recommendation_feedback", to="studio.learningresource")),
                ("target_lesson", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_cta_recommendation_feedback", to="studio.lesson")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resource_cta_recommendations_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-last_seen_at",),
                "indexes": [models.Index(fields=["resource", "status", "last_seen_at"], name="studio_reso_resource_304d4f_idx"), models.Index(fields=["target_type", "status"], name="studio_reso_target__cb63fd_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="resourcectarecommendationfeedback",
            constraint=models.UniqueConstraint(fields=("resource", "recommendation_key"), name="unique_resource_cta_recommendation_feedback"),
        ),
    ]
