# Generated by ChatGPT for phase 32 recommendation tuning controls.

from django.db import migrations, models
import django.core.validators


def seed_default_tuning(apps, schema_editor):
    RecommendationTuning = apps.get_model("studio", "RecommendationTuning")
    RecommendationTuning.objects.get_or_create(
        pk=1,
        defaults={
            "name": "Default recommendation tuning",
            "is_active": True,
            "notes": "Default Code with Michael CTA recommendation weights.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0023_resource_cta_recommendation_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationTuning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Default recommendation tuning", max_length=120)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("lesson_cta_bonus", models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)])),
                ("quiz_cta_bonus", models.IntegerField(default=35, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)])),
                ("challenge_cta_bonus", models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)])),
                ("pdf_open_bonus", models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)])),
                ("pdf_lead_magnet_bonus", models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)])),
                ("newsletter_cta_bonus", models.IntegerField(default=35, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(200)])),
                ("related_lesson_weight", models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("category_match_weight", models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ("difficulty_match_weight", models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("topic_overlap_weight", models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("topic_overlap_cap", models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ("active_quiz_weight", models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("active_challenge_weight", models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("practice_code_weight", models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("conversion_weight", models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("conversion_cap", models.IntegerField(default=48, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ("cta_click_weight", models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("cta_click_cap", models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ("exact_accepted_boost", models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("exact_dismissed_penalty", models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)])),
                ("ignored_per_show_penalty", models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("ignored_penalty_cap", models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("similar_accepted_boost", models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("similar_accepted_cap", models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("similar_dismissed_penalty", models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("similar_dismissed_cap", models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("similar_ignored_penalty", models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("similar_ignored_cap", models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("same_lesson_accepted_boost", models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("same_lesson_accepted_cap", models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("same_lesson_dismissed_penalty", models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("same_lesson_dismissed_cap", models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ("feedback_adjustment_floor", models.IntegerField(default=-120, validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(0)])),
                ("feedback_adjustment_ceiling", models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "recommendation tuning",
                "ordering": ("-is_active", "name"),
            },
        ),
        migrations.RunPython(seed_default_tuning, migrations.RunPython.noop),
    ]
