# Generated by Django 6.0.3 on 2026-07-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_rename_studio_cont_sched__26d7b1_idx_studio_cont_schedul_9e6c57_idx_and_more'),
        ('studio', '0023_resource_cta_recommendation_feedback'),
    ]

    operations = [
    ]
