# Generated by Django 6.0.3 on 2026-07-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0024_merge_20260727_0710'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learningresource',
            new_name='studio_lear_status_ee5506_idx',
            old_name='studio_lear_status_39960c_idx',
        ),
        migrations.RenameIndex(
            model_name='learningresource',
            new_name='studio_lear_feature_dfb780_idx',
            old_name='studio_lear_feature_23f4c6_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecta',
            new_name='studio_reso_resourc_8a8d4e_idx',
            old_name='studio_reso_res_is_a_4d6f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecta',
            new_name='studio_reso_target__9b797d_idx',
            old_name='studio_reso_targ_is_3f85cc_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcectaclickevent',
            new_name='studio_reso_resourc_e35c36_idx',
            old_name='studio_reso_res_occ_b39034_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcectaclickevent',
            new_name='studio_reso_cta_id_00bbbd_idx',
            old_name='studio_reso_cta_occ_4e1ed2_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcectaclickevent',
            new_name='studio_reso_target__d5b156_idx',
            old_name='studio_reso_targ_oc_52dafc_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcectarecommendationfeedback',
            new_name='studio_reso_resourc_c13fa9_idx',
            old_name='studio_reso_resource_304d4f_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcectarecommendationfeedback',
            new_name='studio_reso_target__44b86b_idx',
            old_name='studio_reso_target__cb63fd_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceleadmagnetaccess',
            new_name='studio_reso_resourc_a01cf7_idx',
            old_name='studio_reso_resourc_b88487_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceleadmagnetaccess',
            new_name='studio_reso_email_8d6cc3_idx',
            old_name='studio_reso_email_8c3345_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcelessonconversionevent',
            new_name='studio_reso_resourc_c1606e_idx',
            old_name='studio_reso_resourc_8b9751_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcelessonconversionevent',
            new_name='studio_reso_lesson__d0831f_idx',
            old_name='studio_reso_lesson__e3e47d_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcelessonconversionevent',
            new_name='studio_reso_event_t_2957c7_idx',
            old_name='studio_reso_event_t_9f8277_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcelessonconversionevent',
            new_name='studio_reso_email_301ec3_idx',
            old_name='studio_reso_email_9f9c15_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceperformanceevent',
            new_name='studio_reso_resourc_f079a0_idx',
            old_name='studio_reso_resourc_b114ed_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceperformanceevent',
            new_name='studio_reso_event_t_d7720c_idx',
            old_name='studio_reso_event_t_3f2165_idx',
        ),
        migrations.AlterField(
            model_name='resourcectaclickevent',
            name='cta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='studio.resourcecta'),
        ),
        migrations.AlterField(
            model_name='resourcelessonconversionevent',
            name='cta',
            field=models.ForeignKey(blank=True, help_text='Resource CTA block that received click attribution when available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_events', to='studio.resourcecta'),
        ),
        migrations.AlterField(
            model_name='subscribersegment',
            name='source_filter',
            field=models.CharField(blank=True, choices=[('any', 'Any source'), ('learn_home', 'Learn homepage'), ('lesson', 'Lesson page'), ('resource', 'Resource download'), ('playground', 'Playground'), ('import', 'Imported'), ('studio', 'Studio'), ('other', 'Other')], default='any', help_text='Limit the segment to subscribers from a specific signup source.', max_length=30),
        ),
    ]
