# Generated by Code with Michael Studio phase 34.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0024_recommendation_tuning"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationTuningChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("manual_update", "Manual update"), ("preset_applied", "Preset applied")], db_index=True, max_length=30)),
                ("preset_key", models.CharField(blank=True, max_length=80)),
                ("preset_name", models.CharField(blank=True, max_length=120)),
                ("reason", models.TextField(blank=True)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("diff", models.JSONField(blank=True, default=dict)),
                ("request_path", models.CharField(blank=True, max_length=300)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recommendation_tuning_changes", to=settings.AUTH_USER_MODEL)),
                ("tuning", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="change_logs", to="studio.recommendationtuning")),
            ],
            options={
                "verbose_name": "recommendation tuning change log",
                "verbose_name_plural": "recommendation tuning change logs",
                "ordering": ("-created_at", "-pk"),
            },
        ),
    ]
