# Generated by Django 6.0.3 on 2026-07-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0024_recommendation_tuning'),
        ('studio', '0025_rename_studio_lear_status_39960c_idx_studio_lear_status_ee5506_idx_and_more'),
    ]

    operations = [
    ]
