# Generated by Django 6.0.3 on 2026-07-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0026_merge_20260727_0712'),
        ('studio', '0028_experiment_decision_tuning'),
    ]

    operations = [
    ]
