# Generated by Django 6.0.3 on 2026-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0029_merge_20260728_0724'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendationtuningexperimentsnapshot',
            new_name='studio_reco_change__131b39_idx',
            old_name='studio_reco_change__d6de3f_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationtuningexperimentsnapshot',
            new_name='studio_reco_before__f74f2b_idx',
            old_name='studio_reco_before__fcda6a_idx',
        ),
        migrations.AlterField(
            model_name='recommendationtuningchangelog',
            name='action',
            field=models.CharField(choices=[('manual_update', 'Manual update'), ('preset_applied', 'Preset applied'), ('rollback_restored', 'Rollback restored')], db_index=True, max_length=30),
        ),
    ]
