# Generated by Code with Michael Content Studio phase 45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0031_experiment_decision_rule_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentDecisionTuningSnapshotComparisonReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                ("preset_keys", models.JSONField(blank=True, default=list, help_text="Decision-rule preset keys included when this comparison is rendered.")),
                ("notes", models.TextField(blank=True, help_text="Observations, interpretation, and follow-up decisions for this saved comparison.")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_rule_snapshot_comparison_reports_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_rule_snapshot_comparison_reports_updated", to=settings.AUTH_USER_MODEL)),
                ("snapshots", models.ManyToManyField(blank=True, related_name="saved_comparison_reports", to="studio.experimentdecisiontuningexperimentsnapshot")),
            ],
            options={
                "verbose_name": "decision-rule snapshot comparison report",
                "verbose_name_plural": "decision-rule snapshot comparison reports",
                "ordering": ("-updated_at", "-pk"),
                "indexes": [models.Index(fields=["title", "updated_at"], name="studio_expe_title_0e441d_idx")],
            },
        ),
    ]
