# Generated by Code with Michael Content Studio phase 48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0032_decision_rule_snapshot_comparison_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="decision_status",
            field=models.CharField(choices=[("undecided", "No decision yet"), ("keep", "Keep"), ("roll_back", "Roll back"), ("watch", "Watch"), ("archived", "Archived")], db_index=True, default="undecided", help_text="Final or current decision for this saved comparison report.", max_length=20),
        ),
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="decision_summary",
            field=models.CharField(blank=True, help_text="Short decision statement, such as keep the lead-magnet rules for another two weeks.", max_length=240),
        ),
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="decision_notes",
            field=models.TextField(blank=True, help_text="Decision rationale, follow-up actions, risks, or rollback/watch criteria."),
        ),
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="decision_owner",
            field=models.ForeignKey(blank=True, help_text="Person responsible for following up on this report decision.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_rule_snapshot_comparison_reports_owned", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="decision_recorded_by",
            field=models.ForeignKey(blank=True, help_text="Staff user who last recorded a report decision.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_rule_snapshot_comparison_report_decisions_recorded", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="decision_recorded_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            index=models.Index(fields=["decision_status", "updated_at"], name="studio_expe_decisio_8a90d5_idx"),
        ),
    ]
