# Generated by Django 6.0.3 on 2026-07-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0033_comparison_report_decision_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experimentdecisiontuningexperimentsnapshot',
            new_name='studio_expe_change__e53e2e_idx',
            old_name='studio_exp_change__b9f42c_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningexperimentsnapshot',
            new_name='studio_expe_before__6fb681_idx',
            old_name='studio_exp_before__ced53d_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreport',
            new_name='studio_expe_title_e2fa5b_idx',
            old_name='studio_expe_title_0e441d_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreport',
            new_name='studio_expe_decisio_b2e20d_idx',
            old_name='studio_expe_decisio_8a90d5_idx',
        ),
        migrations.AlterField(
            model_name='experimentdecisiontuningchangelog',
            name='action',
            field=models.CharField(choices=[('manual_update', 'Manual update'), ('preset_applied', 'Preset applied'), ('rollback_restored', 'Rollback restored')], db_index=True, max_length=30),
        ),
    ]
