# Generated by ChatGPT for phase 49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0033_comparison_report_decision_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original saved comparison report this report was cloned from, when applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="studio.experimentdecisiontuningsnapshotcomparisonreport",
            ),
        ),
    ]
