# Generated by ChatGPT for Content Studio phase 50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0034_comparison_report_cloning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentDecisionTuningSnapshotComparisonReportTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("template_type", models.CharField(choices=[("monthly_growth", "Monthly Growth Review"), ("lead_magnet", "Lead Magnet Review"), ("instagram_experiment", "Instagram Experiment Review"), ("learning_conversion", "Learning Conversion Review"), ("custom", "Custom")], db_index=True, default="custom", max_length=40)),
                ("description", models.TextField(blank=True)),
                ("default_report_title", models.CharField(blank=True, help_text="Optional title seed used when creating a report from this template.", max_length=180)),
                ("default_description", models.TextField(blank=True)),
                ("default_notes", models.TextField(blank=True, help_text="Default analysis prompts, checklist items, or review notes copied into new reports.")),
                ("default_preset_keys", models.JSONField(blank=True, default=list, help_text="Decision-rule preset keys included by default when a report is created from this template.")),
                ("recommended_snapshot_count", models.PositiveSmallIntegerField(default=3, help_text="Suggested number of recent snapshots to preselect when creating a report.")),
                ("recommended_window_days", models.PositiveSmallIntegerField(default=14, help_text="Recommended experiment snapshot window for this review type.")),
                ("focus_areas", models.JSONField(blank=True, default=list, help_text="Human-readable focus areas such as follower growth, PDF downloads, or learner conversions.")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_rule_snapshot_comparison_report_templates_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_rule_snapshot_comparison_report_templates_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "decision-rule comparison report template",
                "verbose_name_plural": "decision-rule comparison report templates",
                "ordering": ("template_type", "title"),
                "indexes": [models.Index(fields=["template_type", "is_active"], name="studio_expe_templat_53ff77_idx"), models.Index(fields=["slug"], name="studio_expe_slug_4392b0_idx")],
            },
        ),
    ]
