# Generated by ChatGPT for Content Studio phase 51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0035_decision_rule_comparison_report_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Report template used to create this saved comparison report, when applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_reports",
                to="studio.experimentdecisiontuningsnapshotcomparisonreporttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="experimentdecisiontuningsnapshotcomparisonreport",
            index=models.Index(fields=["source_template", "updated_at"], name="studio_expe_source__f7e6e8_idx"),
        ),
    ]
