# Generated by Code with Michael phase 53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0036_report_template_usage_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentDecisionTuningSnapshotComparisonReportTemplateRecommendationFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recommendation_key", models.CharField(db_index=True, max_length=180)),
                ("status", models.CharField(choices=[("shown", "Shown / ignored"), ("useful", "Useful"), ("dismissed", "Dismissed"), ("revisit", "Revisit later")], db_index=True, default="shown", max_length=20)),
                ("score", models.IntegerField(default=0)),
                ("priority", models.CharField(blank=True, max_length=20)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("suggested_snapshot_ids", models.JSONField(blank=True, default=list)),
                ("times_shown", models.PositiveIntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("responded_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="report_template_recommendation_feedback_created", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recommendation_feedback", to="studio.experimentdecisiontuningsnapshotcomparisonreporttemplate")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="report_template_recommendation_feedback_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "report-template recommendation feedback",
                "verbose_name_plural": "report-template recommendation feedback",
                "ordering": ("-last_seen_at", "template__title"),
                "unique_together": {("template", "recommendation_key", "created_by")},
            },
        ),
        migrations.AddIndex(
            model_name="experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback",
            index=models.Index(fields=["status", "last_seen_at"], name="studio_expe_status_0f5a9b_idx"),
        ),
        migrations.AddIndex(
            model_name="experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback",
            index=models.Index(fields=["template", "status"], name="studio_expe_templat_8996f1_idx"),
        ),
        migrations.AddIndex(
            model_name="experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback",
            index=models.Index(fields=["recommendation_key", "status"], name="studio_expe_recomme_c1ee7b_idx"),
        ),
    ]
