# Generated by Django 6.0.3 on 2026-07-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0034_rename_studio_exp_change__b9f42c_idx_studio_expe_change__e53e2e_idx_and_more'),
        ('studio', '0037_report_template_recommendation_feedback'),
    ]

    operations = [
    ]
