# Generated by phase 55.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0038_report_template_recommendation_tuning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplateRecommendationTuningChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("manual_update", "Manual update"), ("rollback_restored", "Rollback restored")], db_index=True, max_length=30)),
                ("reason", models.TextField(blank=True)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("diff", models.JSONField(blank=True, default=dict)),
                ("request_path", models.CharField(blank=True, max_length=300)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="report_template_recommendation_tuning_changes", to=settings.AUTH_USER_MODEL)),
                ("tuning", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="change_logs", to="studio.reporttemplaterecommendationtuning")),
            ],
            options={
                "verbose_name": "report-template recommendation tuning change",
                "verbose_name_plural": "report-template recommendation tuning changes",
                "ordering": ("-created_at", "-pk"),
                "indexes": [models.Index(fields=["action", "created_at"], name="studio_repo_action_03bc7a_idx"), models.Index(fields=["tuning", "created_at"], name="studio_repo_tuning_177f5b_idx")],
            },
        ),
    ]
