# Generated by Django 6.0.3 on 2026-07-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0038_merge_20260728_2105'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreport',
            new_name='studio_expe_source__d9cdab_idx',
            old_name='studio_expe_source__f7e6e8_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplate',
            new_name='studio_expe_templat_b9d921_idx',
            old_name='studio_expe_templat_53ff77_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplate',
            new_name='studio_expe_slug_aa3d64_idx',
            old_name='studio_expe_slug_4392b0_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback',
            new_name='studio_expe_status_bab972_idx',
            old_name='studio_expe_status_0f5a9b_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback',
            new_name='studio_expe_templat_466b7d_idx',
            old_name='studio_expe_templat_8996f1_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback',
            new_name='studio_expe_recomme_71b20e_idx',
            old_name='studio_expe_recomme_c1ee7b_idx',
        ),
    ]
