# Generated by ChatGPT phase 59

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0041_report_template_recommendation_tuning_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplateRecommendationTuningDecisionRules",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Default template-recommendation decision rules", max_length=140)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("keep_score_threshold", models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ("keep_primary_positive_min", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ("keep_high_confidence_score", models.FloatField(default=18.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ("rollback_score_threshold", models.FloatField(default=-7.0, validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(0)])),
                ("rollback_primary_negative_min", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ("rollback_high_confidence_score", models.FloatField(default=-16.0, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(0)])),
                ("low_confidence_abs_score", models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ("max_metric_change_magnitude", models.FloatField(default=25.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)])),
                ("template_usage_reports_created_weight", models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("saved_reports_reports_created_weight", models.FloatField(default=2.2, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("saved_reports_snapshots_attached_weight", models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("saved_reports_presets_attached_weight", models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("decision_keep_decisions_weight", models.FloatField(default=3.4, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("decision_watch_decisions_weight", models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("feedback_useful_weight", models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("feedback_revisit_weight", models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("feedback_total_actions_weight", models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ("decision_rollback_decisions_penalty", models.FloatField(default=3.6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("decision_archived_decisions_penalty", models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("feedback_dismissed_penalty", models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("feedback_ignored_penalty", models.FloatField(default=1.6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "report-template tuning decision rule",
                "verbose_name_plural": "report-template tuning decision rules",
                "ordering": ("-is_active", "name"),
            },
        ),
    ]
