# Generated by ChatGPT phase 60

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0042_report_template_recommendation_tuning_decision_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplateRecommendationTuningDecisionRulesChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("manual_update", "Manual update"), ("rollback_restored", "Rollback restored")], db_index=True, max_length=30)),
                ("reason", models.TextField(blank=True)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("diff", models.JSONField(blank=True, default=dict)),
                ("request_path", models.CharField(blank=True, max_length=300)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="report_template_recommendation_decision_rule_changes", to=settings.AUTH_USER_MODEL)),
                ("decision_rules", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="change_logs", to="studio.reporttemplaterecommendationtuningdecisionrules")),
            ],
            options={
                "verbose_name": "report-template recommendation decision-rule change",
                "verbose_name_plural": "report-template recommendation decision-rule changes",
                "ordering": ("-created_at", "-pk"),
                "indexes": [models.Index(fields=["action", "created_at"], name="studio_repo_action_b5a1f4_idx"), models.Index(fields=["decision_rules", "created_at"], name="studio_repo_decisio_1f5794_idx")],
            },
        ),
    ]
