# Generated by Django 6.0.3 on 2026-07-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0039_rename_studio_expe_source__f7e6e8_idx_studio_expe_source__d9cdab_idx_and_more'),
        ('studio', '0045_report_template_recommendation_decision_rule_snapshots'),
    ]

    operations = [
    ]
