# Generated by Django 6.0.3 on 2026-07-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0046_merge_20260729_0828'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningchangelog',
            new_name='studio_repo_action_18ed86_idx',
            old_name='studio_repo_action_03bc7a_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningchangelog',
            new_name='studio_repo_tuning__5ac2c0_idx',
            old_name='studio_repo_tuning_177f5b_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningdecisionruleschangelog',
            new_name='studio_repo_action_05b6b3_idx',
            old_name='studio_repo_action_b5a1f4_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningdecisionruleschangelog',
            new_name='studio_repo_decisio_c01db8_idx',
            old_name='studio_repo_decisio_1f5794_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningdecisionrulesexperimentsnapshot',
            new_name='studio_repo_change__3ae100_idx',
            old_name='studio_repo_change__58af53_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningdecisionrulesexperimentsnapshot',
            new_name='studio_repo_before__c21ae8_idx',
            old_name='studio_repo_before__1efe6f_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningexperimentsnapshot',
            new_name='studio_repo_change__2ebeab_idx',
            old_name='studio_repo_change__cc7512_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningexperimentsnapshot',
            new_name='studio_repo_before__cd2150_idx',
            old_name='studio_repo_before__4c99ac_idx',
        ),
    ]
