# Generated by Django 6.0.3 on 2026-07-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0047_rename_studio_repo_action_03bc7a_idx_studio_repo_action_18ed86_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback',
            new_name='studio_expe_status_69b778_idx',
            old_name='studio_expe_status_bab972_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback',
            new_name='studio_expe_templat_fb736c_idx',
            old_name='studio_expe_templat_466b7d_idx',
        ),
        migrations.RenameIndex(
            model_name='experimentdecisiontuningsnapshotcomparisonreporttemplaterecommendationfeedback',
            new_name='studio_expe_recomme_694ce5_idx',
            old_name='studio_expe_recomme_71b20e_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningdecisionrulesexperimentsnapshot',
            new_name='studio_repo_change__3b4c40_idx',
            old_name='studio_repo_change__3ae100_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplaterecommendationtuningdecisionrulesexperimentsnapshot',
            new_name='studio_repo_before__d569c8_idx',
            old_name='studio_repo_before__c21ae8_idx',
        ),
    ]
